import mongoose from 'mongoose';
import { Toy } from './models/toy.model';

const ageGroups = [
    { ageGroupId: 1, name: '4+ years', description: 'Safe for preschool children, simple play.' },
    { ageGroupId: 2, name: '6+ years', description: 'Standard school-age toys and figures.' },
    { ageGroupId: 3, name: '8+ years', description: 'Advanced play and collectibles for older children.' }
];

const types = [
    { typeId: 1, name: 'Figures', description: 'Standalone collectible pet figures.' },
    { typeId: 2, name: 'Playsets', description: 'Interactive environments and buildings.' },
    { typeId: 3, name: 'Blind Box', description: 'Mystery packaging with surprise items.' },
    { typeId: 4, name: 'Plush Toys', description: 'Soft, huggable fabric toys.' },
    { typeId: 5, name: 'Special Editions', description: 'Rare, limited, or holiday exclusive items.' }
];

const mockToys = [
    {
        toyId: 1,
        name: 'LPS Pet Surprise Season 2',
        permalink: 'lps-pet-surprise-season-2',
        description: 'Unbox your new surprise pet! Each box contains an adorable mystery bobble-head pet friend.',
        targetGroup: 'all',
        productionDate: '2025-01-10',
        price: 999,
        imageUrl: 'http://localhost:3000/00502_LittlestPetShop_Hero_PetSurprise-s2-1L1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 2,
        name: 'LPS Blind Single Pack',
        permalink: 'lps-blind-single-pack',
        description: 'A single mystery pet box perfect for expanding your Littlest Pet Shop collection.',
        targetGroup: 'all',
        productionDate: '2025-01-11',
        price: 799,
        imageUrl: 'http://localhost:3000/00503_LittlestPetShop_Hero_BlindSingles_1L-1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 3,
        name: 'LPS Fin-Tastic Pet Pair',
        permalink: 'lps-fin-tastic-pet-pair',
        description: 'Water-loving aquatic pets complete with cute marine accessories.',
        targetGroup: 'all',
        productionDate: '2025-01-12',
        price: 1499,
        imageUrl: 'http://localhost:3000/00508_LittlestPetShop_Hero_FinTastic-1L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 4,
        name: 'LPS Beach Besties Set',
        permalink: 'lps-beach-besties-set',
        description: 'Enjoy the sunny shores with these adorable beach-themed pet besties.',
        targetGroup: 'girls',
        productionDate: '2025-02-01',
        price: 1599,
        imageUrl: 'http://localhost:3000/00517_LittlestPetShop_Hero_BeachBesties-1L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 5,
        name: 'LPS Safari Play Pack',
        permalink: 'lps-safari-play-pack',
        description: 'Go on a wild jungle adventure with wild safari pets and themed gear.',
        targetGroup: 'all',
        productionDate: '2025-02-10',
        price: 3499,
        imageUrl: 'http://localhost:3000/00524_LittlestPetShop_Hero_SafariPlayPack_1L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 6,
        name: 'LPS Sweet & Stylish Dalmatian',
        permalink: 'lps-sweet-stylish-dalmatian',
        description: 'Super stylish spotted puppy figure ready for fashion dress-up fun.',
        targetGroup: 'girls',
        productionDate: '2025-03-05',
        price: 1299,
        imageUrl: 'http://localhost:3000/00530_-LittlestPetShop_Hero_SweetStylish-262-Dalmatian-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 7,
        name: 'LPS Snowy Day Playset',
        permalink: 'lps-snowy-day-playset',
        description: 'Winter-themed pets enjoying sledding and chilly snowy adventures.',
        targetGroup: 'all',
        productionDate: '2024-11-20',
        price: 1499,
        imageUrl: 'http://localhost:3000/00534_LittlestPetShop_Hero_SnowyDay_1L1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 8,
        name: 'LPS 3-Pack Pet Tubes',
        permalink: 'lps-3-pack-pet-tubes',
        description: 'Triple the fun! Includes three mystery bobble-head pets in a clear collector tube.',
        targetGroup: 'all',
        productionDate: '2025-01-15',
        price: 1999,
        imageUrl: 'http://localhost:3000/00556_LittlestPetShop_Hero_3PackTubes_1L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 9,
        name: 'LPS Pet Surprise Wave 1',
        permalink: 'lps-pet-surprise-wave-1',
        description: 'The original Wave 1 mystery single box featuring classic beloved pet molds.',
        targetGroup: 'all',
        productionDate: '2024-09-01',
        price: 899,
        imageUrl: 'http://localhost:3000/00564_LittlestPetShop_Hero_PetSurprise-W1-1L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 10,
        name: 'LPS Winter Besties',
        permalink: 'lps-winter-besties',
        description: 'Cozy up with these fluffy winter pets equipped with earmuffs and scarves.',
        targetGroup: 'girls',
        productionDate: '2024-12-05',
        price: 1699,
        imageUrl: 'http://localhost:3000/00573_LittlestPetShop_HERO_WinterBesties1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 11,
        name: 'LPS Deluxe Pet Shop Playset',
        permalink: 'lps-deluxe-pet-shop-playset',
        description: 'The flagship playset with multiple rooms, spinning towers, and play zones.',
        targetGroup: 'all',
        productionDate: '2025-04-01',
        price: 5499,
        imageUrl: 'http://localhost:3000/00575_LittlestPetShop_Hero_PetShopPlayset_1L1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 12,
        name: 'LPS Jump For Joy Pack',
        permalink: 'lps-jump-for-joy-pack',
        description: 'Energetic pets that love bouncing on trampolines and playing agility games.',
        targetGroup: 'boys',
        productionDate: '2025-03-22',
        price: 1699,
        imageUrl: 'http://localhost:3000/00584_LittlestPetShop_Hero_JumpForJoy-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 13,
        name: 'LPS Pawsitive Chill Pet Pair',
        permalink: 'lps-pawsitive-chill-pet-pair',
        description: 'Two relaxed pet friends who love lounging around and taking easy nap days.',
        targetGroup: 'all',
        productionDate: '2025-02-18',
        price: 1399,
        imageUrl: 'http://localhost:3000/00585_LittlestPetShop_Hero_PawsitiveChillPetPair-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 14,
        name: 'LPS Zoo Cool Pet Pairs',
        permalink: 'lps-zoo-cool-pet-pairs',
        description: 'Cool wild pet duos ready to make any zoo display pop.',
        targetGroup: 'all',
        productionDate: '2025-02-20',
        price: 1499,
        imageUrl: 'http://localhost:3000/00586_LittlestPetShop_Hero_ZooCoolPetPairs-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 15,
        name: 'LPS Lop Leap Pet Pair',
        permalink: 'lps-lop-leap-pet-pair',
        description: 'Bouncing bunny pets with soft long ears and carrot snack accessories.',
        targetGroup: 'girls',
        productionDate: '2025-03-01',
        price: 1399,
        imageUrl: 'http://localhost:3000/00587_LittlestPetShop_Hero_LopLeapPetPair-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 16,
        name: 'LPS Luxury Pet Hotel',
        permalink: 'lps-luxury-pet-hotel',
        description: 'A 5-star hotel destination for pampering your bobble-head pets.',
        targetGroup: 'girls',
        productionDate: '2025-05-10',
        price: 4999,
        imageUrl: 'http://localhost:3000/00595_LittlestPetShop_Hero_PetHotel1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 17,
        name: 'LPS Zoo Pets Trio',
        permalink: 'lps-zoo-pets-trio',
        description: 'Three exotic zoo pals packaged together for instant wildlife fun.',
        targetGroup: 'all',
        productionDate: '2025-02-25',
        price: 2199,
        imageUrl: 'http://localhost:3000/00597_LittlestPetShop_Hero_ZooPetsPetTrio1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 18,
        name: 'LPS Park Pets Trio',
        permalink: 'lps-park-pets-trio',
        description: 'Three pet friends who spend their afternoons playing tag at the park.',
        targetGroup: 'all',
        productionDate: '2025-01-25',
        price: 2199,
        imageUrl: 'http://localhost:3000/00598_LittlestPetShop_Hero_PetTrio_ParkPets-11-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 19,
        name: 'LPS Pet Surprise Wave 2',
        permalink: 'lps-pet-surprise-wave-2',
        description: 'Second wave mystery single boxes with fresh new collector numbers.',
        targetGroup: 'all',
        productionDate: '2025-02-05',
        price: 899,
        imageUrl: 'http://localhost:3000/00599_LittlestPetShop_Hero_PetSurprise-W2-1L2-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 20,
        name: 'LPS Winter Pals Set',
        permalink: 'lps-winter-pals-set',
        description: 'A 3-pack bundle of arctic pets ready for cold weather fun.',
        targetGroup: 'all',
        productionDate: '2024-11-15',
        price: 2299,
        imageUrl: 'http://localhost:3000/00603_LittlestPetShop_Hero_WinterPals_3L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 21,
        name: 'LPS Winter Trio Blind Box',
        permalink: 'lps-winter-trio-blind-box',
        description: 'A holiday surprise box packed with three mysterious snowy pets.',
        targetGroup: 'all',
        productionDate: '2024-12-01',
        price: 1999,
        imageUrl: 'http://localhost:3000/00605_LittlestPetShop_HERO_WinTrioBlindBox1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 22,
        name: 'LPS Holiday Advent Calendar',
        permalink: 'lps-holiday-advent-calendar',
        description: 'Count down the festive season with 24 daily pet and accessory surprises!',
        targetGroup: 'all',
        productionDate: '2024-10-15',
        price: 3299,
        imageUrl: 'http://localhost:3000/00609_LittlestPetShop_Hero_AdventCalendar2-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[4]
    },
    {
        toyId: 23,
        name: 'LPS Traveling Adventure Pack',
        permalink: 'lps-traveling-adventure-pack',
        description: 'Pets equipped with suitcases and sunglasses for world travels.',
        targetGroup: 'all',
        productionDate: '2025-03-10',
        price: 2399,
        imageUrl: 'http://localhost:3000/00618_LittlestPetShop_Hero_TravelingAdventure_3L1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 24,
        name: 'LPS Cozy Picnic Spot',
        permalink: 'lps-cozy-picnic-spot',
        description: 'A delightful park picnic setup complete with miniature food treats.',
        targetGroup: 'girls',
        productionDate: '2025-04-12',
        price: 1899,
        imageUrl: 'http://localhost:3000/00624_LittlestPetShop_Hero_PicnicSpot-3L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[1]
    },
    {
        toyId: 25,
        name: 'LPS Cowabunga Surfer Set',
        permalink: 'lps-cowabunga-surfer-set',
        description: 'Beach bum pets riding miniature surfboards on ocean waves.',
        targetGroup: 'boys',
        productionDate: '2025-03-15',
        price: 1799,
        imageUrl: 'http://localhost:3000/00625_LittlestPetShop_Hero_Cowabunga-3L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 26,
        name: 'LPS Look-Alikes Twin Pack',
        permalink: 'lps-look-alikes-twin-pack',
        description: 'Matching twin pets with funny contrasting expression details.',
        targetGroup: 'all',
        productionDate: '2025-02-14',
        price: 1599,
        imageUrl: 'http://localhost:3000/00626_LittlestPetShop_Hero_LookAlikes-3L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 27,
        name: 'LPS Treasure Hunt Set',
        permalink: 'lps-treasure-hunt-set',
        description: 'Pirate-themed pets hunting for hidden chests and golden coins.',
        targetGroup: 'boys',
        productionDate: '2025-03-01',
        price: 2099,
        imageUrl: 'http://localhost:3000/00627_LittlestPetShop_Hero_TreasureHunt-3L-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 28,
        name: 'LPS Diner Dash Playset',
        permalink: 'lps-diner-dash-playset',
        description: 'Serve up miniature burgers and shakes at the pet diner station.',
        targetGroup: 'all',
        productionDate: '2025-03-30',
        price: 2499,
        imageUrl: 'http://localhost:3000/00636_LittlestPetShop_Hero_DinerDash-1-300x300.png',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 29,
        name: 'LPS Pet Disco Nights',
        permalink: 'lps-pet-disco-nights',
        description: 'Dance party set with glittery pets and a revolving dancefloor.',
        targetGroup: 'girls',
        productionDate: '2025-04-05',
        price: 2799,
        imageUrl: 'http://localhost:3000/00637_LittlestPetShop_Hero_PetDiscoNights_1L-1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 30,
        name: 'LPS Pet Grooming Spa',
        permalink: 'lps-pet-grooming-spa',
        description: 'Pamper your pets with miniature tubs, brushes, and salon chairs.',
        targetGroup: 'girls',
        productionDate: '2025-02-28',
        price: 2299,
        imageUrl: 'http://localhost:3000/00638_LittlestPetShop_Hero_GroomingSpa-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[1]
    },
    {
        toyId: 31,
        name: 'LPS Springtime Fun Pack',
        permalink: 'lps-springtime-fun-pack',
        description: 'Flower-adorned pets celebrating springtime outdoors.',
        targetGroup: 'girls',
        productionDate: '2025-03-20',
        price: 1499,
        imageUrl: 'http://localhost:3000/00650_LittlestPetShop_Hero_SpringTimeFun-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 32,
        name: 'LPS Trio Blind Box',
        permalink: 'lps-trio-blind-box',
        description: 'A large surprise box holding three unrevealed collector pets.',
        targetGroup: 'all',
        productionDate: '2025-01-20',
        price: 1899,
        imageUrl: 'http://localhost:3000/00651_LittlestPetShop_Hero_TrioBlindBox-1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 33,
        name: 'LPS Small Plush Friend',
        permalink: 'lps-small-plush-friend',
        description: 'Soft and squeezable plush version of iconic Littlest Pet Shop pets.',
        targetGroup: 'all',
        productionDate: '2024-10-01',
        price: 1199,
        imageUrl: 'http://localhost:3000/00660_LittlestPetShop_Hero_SmallPlush-1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[3]
    },
    {
        toyId: 34,
        name: 'LPS Spotty Cow Figure',
        permalink: 'lps-spotty-cow-figure',
        description: 'Adorable black-and-white spotted farm cow figure with big eyes.',
        targetGroup: 'all',
        productionDate: '2025-01-08',
        price: 1299,
        imageUrl: 'http://localhost:3000/00666_LittlestPetShop_Hero_Cow-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 35,
        name: 'LPS Playful Penguin',
        permalink: 'lps-playful-penguin',
        description: 'Cute waddling penguin figure ready for icy adventures.',
        targetGroup: 'all',
        productionDate: '2024-12-01',
        price: 1199,
        imageUrl: 'http://localhost:3000/00668_LittlestPetShop_Hero_Penguin-2-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 36,
        name: 'LPS Bamboo Panda Figure',
        permalink: 'lps-bamboo-panda-figure',
        description: 'Rare panda figure complete with a miniature green bamboo branch.',
        targetGroup: 'all',
        productionDate: '2025-01-05',
        price: 1399,
        imageUrl: 'http://localhost:3000/00669_LittlestPetShop_Hero_Panda-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[4]
    },
    {
        toyId: 37,
        name: 'LPS Cuddly Medium Plush',
        permalink: 'lps-cuddly-medium-plush',
        description: 'Hug-sized plush companion crafted with extra soft fabric.',
        targetGroup: 'all',
        productionDate: '2024-11-01',
        price: 1899,
        imageUrl: 'http://localhost:3000/00670_LittlestPetShop_Item_MediumPlush-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[3]
    },
    {
        toyId: 38,
        name: 'LPS Pet Pair Blind Pack',
        permalink: 'lps-pet-pair-blind-pack',
        description: 'Double surprise! Two mystery pets concealed inside a single box.',
        targetGroup: 'all',
        productionDate: '2025-02-12',
        price: 1499,
        imageUrl: 'http://localhost:3000/00680_LittlestPetShop_Hero_PetPairBlinds-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 39,
        name: 'LPS Foodie Treats Pack',
        permalink: 'lps-foodie-treats-pack',
        description: 'Pets obsessed with snacks, packaged with food-shaped accessories.',
        targetGroup: 'all',
        productionDate: '2025-03-08',
        price: 1599,
        imageUrl: 'http://localhost:3000/00690_LittlestPetShop_Hero_FoodieTreats-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 40,
        name: 'LPS Campfire Fun Playset',
        permalink: 'lps-campfire-fun-playset',
        description: 'Outdoorsy pets roasting marshmallow treats around a toy campfire.',
        targetGroup: 'all',
        productionDate: '2025-04-02',
        price: 2199,
        imageUrl: 'http://localhost:3000/00692_LittlestPetShop_Hero_Campfire-1L-1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 41,
        name: 'LPS Trio Blind Tube Series 3',
        permalink: 'lps-trio-blind-tube-series-3',
        description: 'Series 3 collector tube with three unknown pets waiting inside.',
        targetGroup: 'all',
        productionDate: '2025-03-12',
        price: 1999,
        imageUrl: 'http://localhost:3000/00696_LittlestPetShop_Hero_PetTrioBlindTubes_s3-2-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 42,
        name: 'LPS Elephant Spa Day Pair',
        permalink: 'lps-elephant-spa-day-pair',
        description: 'Sweet baby elephant paired with a spa bathtub and soap bubble props.',
        targetGroup: 'girls',
        productionDate: '2025-02-28',
        price: 1799,
        imageUrl: 'http://localhost:3000/00706_LittlestPetShop_Hero_PetPairs_ElephantSpa-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[1]
    },
    {
        toyId: 43,
        name: 'LPS Beach Bites Snack Set',
        permalink: 'lps-beach-bites-snack-set',
        description: 'Seaside pets enjoying ice cream cones and fruity drinks.',
        targetGroup: 'all',
        productionDate: '2025-03-18',
        price: 1399,
        imageUrl: 'http://localhost:3000/00707_LittlestPetShop_Hero_BeachBites-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 44,
        name: 'LPS Country Cottage Picnic',
        permalink: 'lps-country-cottage-picnic',
        description: 'A rustic cottage-themed setting for afternoon pet tea parties.',
        targetGroup: 'girls',
        productionDate: '2025-04-15',
        price: 2899,
        imageUrl: 'http://localhost:3000/00708_LittlestPetShop_Hero_CottagePicnic-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 45,
        name: 'LPS Stylin Stripes Pet',
        permalink: 'lps-stylin-stripes-pet',
        description: 'Boldly striped tiger and zebra figures with funky hair clips.',
        targetGroup: 'all',
        productionDate: '2025-02-10',
        price: 1399,
        imageUrl: 'http://localhost:3000/00709_LittlestPetShop_Hero_StylinStripes-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 46,
        name: 'LPS Blind Single Counter Box',
        permalink: 'lps-blind-single-counter-box',
        description: 'A store display edition single box featuring wave 1 artwork.',
        targetGroup: 'all',
        productionDate: '2024-09-15',
        price: 799,
        imageUrl: 'http://localhost:3000/00717_LittlestPetShop_Hero_BlindSingles-CDU_1L-1-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 47,
        name: 'LPS Blind Single Series 5',
        permalink: 'lps-blind-single-series-5',
        description: 'Series 5 individual mystery box with updated checklist catalog.',
        targetGroup: 'all',
        productionDate: '2025-04-01',
        price: 899,
        imageUrl: 'http://localhost:3000/00718_LittlestPetShop_Hero_BlindSingles_s5-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 48,
        name: 'LPS Collector Display Case',
        permalink: 'lps-collector-display-case',
        description: 'A multi-tier plastic display stand built to showcase over 30 pets.',
        targetGroup: 'all',
        productionDate: '2025-01-30',
        price: 3999,
        imageUrl: 'http://localhost:3000/00721_LittlestPetShop_Hero_CollectDisplayAmazon-300x300.jpg',
        active: true,
        ageGroup: ageGroups[2],
        type: types[4]
    },
    {
        toyId: 49,
        name: 'LPS Beauty Style Station',
        permalink: 'lps-beauty-style-station',
        description: 'Styling mirror station equipped with ribbon accessories and bow ties.',
        targetGroup: 'girls',
        productionDate: '2025-03-25',
        price: 2599,
        imageUrl: 'http://localhost:3000/00722_LittlestPetShop_Hero_StyleStation-5-200x200.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 50,
        name: 'LPS Pet Surprise Trio Box',
        permalink: 'lps-pet-surprise-trio-box',
        description: 'A 3-in-1 surprise package loaded with mystery bobble-heads.',
        targetGroup: 'all',
        productionDate: '2025-02-01',
        price: 1999,
        imageUrl: 'http://localhost:3000/00723_LittlestPetShop_HERO_PetSurpriseTrio_Blind-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 51,
        name: 'LPS Surprise Trio Tube Series 4',
        permalink: 'lps-surprise-trio-tube-series-4',
        description: 'Clear cylinder tube packed with three undisclosed figures.',
        targetGroup: 'all',
        productionDate: '2025-04-10',
        price: 1999,
        imageUrl: 'http://localhost:3000/00739_LittlestPetShop_Hero_BlindTrioTubes-300x300.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 52,
        name: 'LPS Fashion Pet Boutique',
        permalink: 'lps-fashion-pet-boutique',
        description: 'Trendy clothing boutique playset featuring miniature hats and glasses.',
        targetGroup: 'girls',
        productionDate: '2025-04-20',
        price: 2699,
        imageUrl: 'http://localhost:3000/00744_LittlestPetShop_Hero_PetBoutique-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[1]
    },
    {
        toyId: 53,
        name: 'LPS Pet Pairs Collector Bundle',
        permalink: 'lps-pet-pairs-collector-bundle',
        description: 'A mega-pack containing multiple pet pairs and bonus accessories.',
        targetGroup: 'all',
        productionDate: '2025-03-01',
        price: 3499,
        imageUrl: 'http://localhost:3000/00746_LittlestPetShop_HERO_PetPairsBundle-300x300.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[0]
    },
    {
        toyId: 54,
        name: 'LPS Deluxe Collector Pack',
        permalink: 'lps-deluxe-collector-pack',
        description: 'Includes rare metallic-painted pets and exclusive collector cards.',
        targetGroup: 'all',
        productionDate: '2025-02-15',
        price: 4299,
        imageUrl: 'http://localhost:3000/00747_LittlestPetShop_Hero_LittlestPetShopDeluxe-v1-200x200.jpg',
        active: true,
        ageGroup: ageGroups[2],
        type: types[4]
    },
    {
        toyId: 55,
        name: 'LPS Deluxe Holiday Calendar',
        permalink: 'lps-deluxe-holiday-calendar',
        description: 'Enhanced holiday calendar featuring glitter-coated figures.',
        targetGroup: 'all',
        productionDate: '2024-10-20',
        price: 3699,
        imageUrl: 'http://localhost:3000/00759_LittlestPetShop_Hero_DeluxeAdventCalender2-200x200.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[4]
    },
    {
        toyId: 56,
        name: 'LPS 2-Pack Blind Box Series 5',
        permalink: 'lps-2-pack-blind-box-series-5',
        description: 'Series 5 duo mystery box containing two hidden figures.',
        targetGroup: 'all',
        productionDate: '2025-04-18',
        price: 1399,
        imageUrl: 'http://localhost:3000/01045_LittlestPetShop_Hero_Blind2pk-s5-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 57,
        name: 'LPS Blind Single Series 6',
        permalink: 'lps-blind-single-series-6',
        description: 'Latest Series 6 mystery individual pet boxes.',
        targetGroup: 'all',
        productionDate: '2025-05-01',
        price: 899,
        imageUrl: 'http://localhost:3000/01091_LittlestPetShop_Hero_BlindSinglesS6-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[2]
    },
    {
        toyId: 58,
        name: 'LPS Twisted Tails Pet Pair',
        permalink: 'lps-twisted-tails-pet-pair',
        description: 'Pets with bendable, poseable tails for extra expressive play.',
        targetGroup: 'all',
        productionDate: '2025-03-30',
        price: 1599,
        imageUrl: 'http://localhost:3000/01093_LittlestPetShop_Hero_TwistedTails-3L-200x200.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    },
    {
        toyId: 59,
        name: 'LPS Special Edition Look Pack',
        permalink: 'lps-special-edition-look-pack',
        description: 'Special edition collaboration figure with custom outfit designs.',
        targetGroup: 'girls',
        productionDate: '2025-04-25',
        price: 1899,
        imageUrl: 'http://localhost:3000/01103_LittlestPetShop_Hero_LikeNastya_LikeMyLook-1-200x200.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[4]
    },
    {
        toyId: 60,
        name: 'LPS Special Edition Besties',
        permalink: 'lps-special-edition-besties',
        description: 'Exclusive 2-pack collaboration pets featuring unique eye graphics.',
        targetGroup: 'girls',
        productionDate: '2025-04-28',
        price: 2499,
        imageUrl: 'http://localhost:3000/01141_LittlestPetShop_Hero_LikeNastyaBesties-1-200x200.jpg',
        active: true,
        ageGroup: ageGroups[1],
        type: types[4]
    },
    {
        toyId: 61,
        name: 'LPS Playful Bird Figure',
        permalink: 'lps-playful-bird-figure',
        description: 'A colorful miniature bird figure with a feather crest accessory.',
        targetGroup: 'all',
        productionDate: '2025-05-01',
        price: 1099,
        imageUrl: 'http://localhost:3000/birb.jpg',
        active: true,
        ageGroup: ageGroups[0],
        type: types[0]
    }
];

const seedDatabase = async () => {
    try {
        await mongoose.connect('mongodb://localhost:27017/toy-store');
        console.log('Connected to MongoDB for seeding...');
        await Toy.deleteMany({});
        console.log('Cleared out old toys.');
        await Toy.insertMany(mockToys);
        console.log(`Successfully seeded ${mockToys.length} English LPS records!`);
    } catch (error) {
        console.error('Error seeding the database:', error);
    } finally {
        await mongoose.connection.close();
        console.log('Database connection closed.');
    }
};

seedDatabase();